<?php
    require_once 'includes/lb_core.php';
    $api = new LicenseBoxAPI();
	$app_model = new Application_Model_Application(); 
    $filename = Core_Model_Directory::getBasePathTo("/app/local/modules/TrainingVideos/resources/var/web/modules/trainingvideos/settings.txt");
    $settings = json_decode(file_get_contents($filename),true);
    $channelId = $settings['channel'];
    $headerVisible = $settings['headervisible'];
    $headerLayout = $settings['headerlayout'];
    $headerInfo = $settings['headerinfo'];
    $headerChannelName = $settings['headerchannelname'];
    $headerChannelDescription = $settings['headerchannelescription'];
    $headerChannelLogo = $settings['headerchannellogo'];
    $headerChannelBanner = $settings['headerchannelbanner'];
    $contentColumns = $settings['contentcolumns'];
    $contentRows = $settings['contentrows'];
    $videoInfo = $settings['videoinfo'];
    $colorScheme = $settings['colorscheme'];
    $videoLayout = $settings['videolayout'];
    $ApiKey = $settings['apikey'];
  ?>
<html>

<head>
<meta charset="utf-8"/>
<script src="/app/local/modules/TrainingVideos/resorces/design/desktop/flat/template/trainingvideos/application/js/plugins.min.js"></script>
<script src="/app/local/modules/TrainingVideos/resorces/design/desktop/flat/template/trainingvideos/application/js/main.js"></script>
        <!-- Style CSS -->
        <link rel="stylesheet" href="/app/local/modules/TrainingVideos/resources/design/desktop/flat/template/trainingvideos/application/css/style.css">
        <link rel="stylesheet" href="/app/local/modules/TrainingVideos/resources/design/desktop/flat/template/trainingvideos/application/css/plugins.min.css">
        <link rel="icon" type="image/png" href="img/favicon.png">
        <script src="https://kit.fontawesome.com/fbd64493bb.js" crossorigin="anonymous"></script>
        <script src="/app/local/modules/TrainingVideos/yottie/jquery.yottie.bundled.js"></script>
        <script>
          $(document).ready(function() {
            $("#activation_form_submit").click(function (e) {
                if(($('#license_code').length && $('#license_code').val().length)&&($('#client_name').length && $('#client_name').val().length)){
                    $("#activation_form_submit").html('Loading...');
                    $('#activation_form_submit').prop('disabled', true);
                }else{
                    $("#activation_form_submit").html('Activate');
                    $('#activation_form_submit').prop('disabled', false);
                }
            });
          });
        </script>
</head>
<style>
iframe {
    display:block;
    width:100%;
    height:100vh;
}
.mt-4, .my-4 {
    margin-top: 1.5rem !important;
}
.container {
    width: 50%;
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
}
*, ::after, ::before {
    box-sizing: border-box;
}
.row {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    margin-right: -15px;
    margin-left: -15px;
}
*, ::after, ::before {
    box-sizing: border-box;
}
.col-md-8 {
    -ms-flex: 0 0 66.666667%;
    flex: 0 0 66.666667%;
    max-width: 66.666667%;
}
.form-group {
    margin-bottom: 1rem;
}
*, ::after, ::before {
    box-sizing: border-box;
}
.form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
.form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
.text-muted {
    color: #6c757d !important;
}
.form-text {
    display: block;
    margin-top: .25rem;
}
.small, small {
    font-size: 80%;
    font-weight: 400;
}
small {
    font-size: 80%;
}
*, ::after, ::before {
    box-sizing: border-box;
}
[type="button"]:not(:disabled), [type="reset"]:not(:disabled), [type="submit"]:not(:disabled), button:not(:disabled) {
    cursor: pointer;
    background-color: #67b1ff;
    color: #fff;
}
.btn-primary:hover {
    color: #fff;
    background-color: #0069d9;
    border-color: #0062cc;
}
.btn:hover {
    color: #212529;
    text-decoration: none;
}
[type="button"]:not(:disabled), [type="reset"]:not(:disabled), [type="submit"]:not(:disabled), button:not(:disabled) {
    cursor: pointer;
}
[type="button"], [type="reset"], [type="submit"], button {
    -webkit-appearance: button;
}
.btn {
    display: inline-block;
    font-weight: 400;
    color: #212529;
    text-align: center;
    vertical-align: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-color: transparent;
    border: 1px solid transparent;
        border-top-color: transparent;
        border-right-color: transparent;
        border-bottom-color: transparent;
        border-left-color: transparent;
    border-top-color: transparent;
    border-right-color: transparent;
    border-bottom-color: transparent;
    border-left-color: transparent;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    border-radius: .25rem;
    transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
.btn-primary {
    color: #fff;
    background-color: #007bff;
    border-color: #007bff;
}
.btn-primary {
    color: #fff;
    background-color: #007bff;
    border-color: #007bff;
}
.btn {
    display: inline-block;
    font-weight: 400;
    color: #212529;
    text-align: center;
    vertical-align: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-color: transparent;
    border: 1px solid transparent;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    border-radius: .25rem;
    transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
[type="button"], [type="reset"], [type="submit"], button {
    -webkit-appearance: button;
}
button {
    border-radius: 0;
}
button, input, optgroup, select, textarea {
    margin: 0;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}
button, input {
    overflow: visible;
}
button, select {
    text-transform: none;
}
button, select {
    text-transform: none;
}
button, input {
    overflow: visible;
}
button, input, optgroup, select, textarea {
    margin: 0;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}
button {
    border-radius: 0;
}
*, ::after, ::before {
    box-sizing: border-box;
}
*, ::after, ::before {
    box-sizing: border-box;
}
*, ::after, ::before {
    box-sizing: border-box;
}
*, ::after, ::before {
    box-sizing: border-box;
}
*, ::after, ::before {
    box-sizing: border-box;
}
*, ::after, ::before {
    box-sizing: border-box;
}

</style>
<body>
         
<?php
$res = $api->verify_license();
if($res['status'] != true){
    $license_code = null;
    $client_name = null;
    if(!empty($_POST['license_code'])&&!empty($_POST['client_name'])){
        $license_code = strip_tags(trim($_POST["license_code"]));
        $client_name = strip_tags(trim($_POST["client_name"]));
        $activate_response = $api->activate_license($license_code, $client_name);
        if(empty($activate_response)){
            $msg = 'Server is unavailable.';
        }else{
            $msg = $activate_response['message'];
        }
        if($activate_response['status'] != true){ ?>
            <div class="container mt-4">
                <h2 class="mt-5"><b>TrainingVideos Pro</b> - Activation</h2><hr>
                <div class="row">
                    <div class="col-md-8">
                        <form action="<?php echo $this->getUrl('trainingvideos/application/view'); ?>" method="post">
                            <div class="alert alert-danger" role="alert">
                                <?php echo ucfirst($msg); ?>
                            </div>
                            <div class="form-group">
                                <label for="license_code">License Code*</label>
                                <input type="text" class="form-control" id="license_code" name="license_code" placeholder="Enter your license code" required>
                            </div>
                            <div class="form-group">
                                <label for="client_name">Your Name*</label>
                                <input type="text" class="form-control" id="client_name" name="client_name" placeholder="Enter your name">
                                <small id="emailHelp" class="form-text text-muted">If the license is licensed to a different person, Enter their full name.</small>
                            </div>
                            <button type="submit" class="btn btn-primary" name="activation_form_submit" id="activation_form_submit">Activate</button>
                        </form>
                    </div>
                </div>
            </div>
        <?php } else { ?>
        <div class="container mt-4">
            <h2 class="mt-5"><b>TrainingVideos Pro</b> - Activation</h2><hr>
            <div class="row">
                <div class="col-md-8">
                    <div class="alert alert-success" role="alert">
                    <?php echo ucfirst($msg); ?>
                    </div>
                    <p class="pt-2 text-center">You will be automatically redirected in 3 seconds...</p>
                </div>
            </div>
        </div>
        <script type="text/javascript">    
            setTimeout(function () {
                window.location.href = window.location.href;
            }, 3000);
        </script>
        <?php }
    die("</body></html>"); } else { ?>
    
        <div class="container mt-4">
            <h2 class="mt-5"><b>TrainingVideos Pro</b> - Activation</h2><hr>
            <div class="row">
                <div class="col-md-8">
                    <form action="<?php echo $this->getUrl('trainingvideos/application/view'); ?>" method="post">
                        <div class="form-group">
                            <label for="license_code">License Code*</label>
                            <input type="text" class="form-control" id="license_code" name="license_code" placeholder="Enter your license code" required>
                        </div>
                        <div class="form-group">
                            <label for="client_name">Your Name*</label>
                            <input type="text" class="form-control" id="client_name" name="client_name" placeholder="Enter your name">
                            <small id="emailHelp" class="form-text text-muted">If the license is licensed to a different person, Enter their full name.</small>
                        </div>
                        <button type="submit" class="btn btn-primary" name="activation_form_submit" id="activation_form_submit">Activate</button>
                    </form>
                </div>
            </div>
        </div>
    <?php die("</body></html>"); } } else { ?>
    
<div data-yt
     data-yt-key="<?php echo $ApiKey ?>"
     data-yt-channel="<?php echo $channelId ?>"
     data-yt-width="auto"
     data-yt-lang="en"
     data-yt-header-layout="<?php echo $headerLayout ?>"
     data-yt-header-info="<?php echo $headerInfo ?>"
     data-yt-header-channel-name="<?php echo $headerChannelName ?>"
     data-yt-header-channel-description="<?php echo $headerChannelDescription ?>"
     data-yt-header-channel-logo="<?php echo $headerChannelLogo ?>"
     data-yt-header-channel-banner="<?php echo $headerChannelBanner ?>"
     data-yt-content-columns="<?php echo $contentColumns ?>"
     data-yt-content-rows="<?php echo $contentRows ?>"
	 data-yt-header-visible="<?php echo $headerVisible ?>"
     data-yt-popup-info="false"
     data-yt-color-scheme="<?php echo $colorScheme ?>"
     data-yt-video-info="<?php echo $videoInfo ?>"
     data-yt-video-layout="<?php echo $videoLayout ?>"
	 
</div>

</body>
</html> 

<?php } ?>